spring.application.name=match
spring.mail.username=singhjassu1004@gmail.com
spring.mail.password=buyv xglo ivfr uewc
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
